# Generated by Django 4.2.2 on 2023-07-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id', 'name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='recipes',
            options={'ordering': ['title', 'time_create'], 'verbose_name': 'Recipes', 'verbose_name_plural': 'Recipes'},
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='cat',
        ),
        migrations.AddField(
            model_name='recipes',
            name='cat',
            field=models.ManyToManyField(null=True, related_name='recipes', to='recipes.category'),
        ),
    ]
